name: cosgass
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - astropy
  - h5py
  - matplotlib
  - yt
  - jupyterlab
  - pip
  - pip:
      - trident
      - scida
      - "illustris-python @ git+https://github.com/illustristng/illustris_python.git"
